Add Chapter 5.E rules to "all the rules we know"
alan-turing-institute/hut23-linear-algebra pull request #51
Opened 2024-11-01 11:46 UTC by llewelld

The diff will look cleaner (i.e. without the 5.D section) once #50 has been merged in.

2024-11-01 11:47 UTC, llewelld commented
The usual preview: https://github.com/llewelld/hut23-linear-algebra/blob/gh-action-result/pdf-files/reference/all-the-rules-we-know.pdf

2024-11-01 11:47 UTC, llewelld commented
Another one I'm afraid @rwood-97!

2024-11-04 11:02 UTC, llewelld commented
Rebased.

2024-11-25 12:07 UTC, rwood-97 commented on reference/all-the-rules-we-know.tex
> +\begin{enumerate}
maybe should be a new line here?

2024-11-25 12:07 UTC, rwood-97 requested changes

2024-11-25 12:07 UTC, rwood-97 commented on reference/all-the-rules-we-know.tex
> +Suppose $V$ is a finite-dimensional complex vector space and $S, T$ are commuting operators on $V$. Then there is a basis of $V$ with respect to which both $S$ and $T$ have upeer-triangular matrices.
upper (typo)

2024-11-25 14:16 UTC, llewelld commented on reference/all-the-rules-we-know.tex
> +\begin{enumerate}
Yes, absolutely! Thanks. This should be fixed now.

2024-11-25 14:16 UTC, llewelld commented on reference/all-the-rules-we-know.tex
> +Suppose $V$ is a finite-dimensional complex vector space and $S, T$ are commuting operators on $V$. Then there is a basis of $V$ with respect to which both $S$ and $T$ have upeer-triangular matrices.
Thanks for catching this. It should be fixed now.

2024-11-25 14:17 UTC, llewelld commented
Thanks for reviewing this @rwood-97; I really appreciate it. The issues should be fixed now, but please say if you spot anything further.

2024-11-26 16:25 UTC, rwood-97 approved these changes

2024-11-26 16:26 UTC, rwood-97 commented
Will try do 6A this week too :)

2024-12-13 08:54 UTC, merged